### ISSUE TITLE
task(importAccount): Store Recovery seed in Warp/give user option to delete 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1677]
**Issue:**
Like the title says, we want to store the Users recovery phrase into warp, and give them the option in settings to clear that phrase from Warp

**Comment by dariusc93** [comment]
This can be done by adding `config.save_phrase = true` to  https://github.com/Satellite-im/Uplink/blob/3328f3ab0f641584335691b1390442340d37a0f6/common/src/warp_runner/mod.rs#L383 and add `config.save_phrase = true;`  and then the phrase can be access from tesseract under the name "mnemonic". Note that if an account created or imported without that flag set, it will not be set in tesseract and would require the user to have the phrase at hand.
