### ISSUE TITLE
bug(ui): App buttons and sidebar buttons getting pushed off screen

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1697]
**Issue:**
Sara and Jeff have noticed that sometimes the buttons for the app (minimize, maximize, close) are being renders outside of the app window and some of the sidebar buttons get pushed too. They are not always able to reproduce this, it seems totally random at the moment. Wanted to create a ticket for it here so we can jot down notes from our findings and see what is causing this

**OS:**
So far just MacOS

**Screenshot:**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/3c5b4450-0054-493e-87a0-3898c67dccf3)

**Comment by Jekrimo** [comment]
Going to close this as there has been no reoccurrences since old code clean.
