### ISSUE TITLE
bug(groups): group chat search crash

### ISSUE THREAD

**Issue by Flemmli97** [Satellite-im/Uplink-UI_Kit#1700]
Having a group with special chars in it (e.g. chinese characters) will crash the app when searching.
This is cause we are checking bytes and not chars.
`panicked at common/src/state/mod.rs:1636:18:`

**Comment by lgmarchi** [comment]
@Flemmli97 Could you record a video and post here showing how to replicate this issue?

Because I tested with chinese char here and worked. 


https://github.com/Satellite-im/Uplink/assets/63157656/e495e303-9d3b-4927-a9da-f495d10ed12e

**Comment by dariusc93** [comment]
Could you post the specific error? Looking at the code, i would assume its index out of bounds, which we could easily get around (though the logic could use some improvement/simplifying if comparing two strings), but just want to make sure it is the case and not any other error.

https://github.com/Satellite-im/Uplink/blob/d1326eba157d472d2b3db3dc3e6761079c9daa67/common/src/state/mod.rs#L1632-L1638

**Comment by phillsatellite** [comment]
I was able to replicate a crash without having special chars, I wanted to comment here because it might be related. What I did to reproduce was:
- Search in Group chat search 
- Then search a user/chat in the sidebar search 
- Crash happens 
- ```zsh: segmentation fault  cargo run --release```

https://github.com/Satellite-im/Uplink/assets/93608357/02941707-bbe9-47a6-b741-91385bac89b4

**Comment by Flemmli97** [comment]
> Could you post the specific error? Looking at the code, i would assume its index out of bounds, which we could easily get around (though the logic could use some improvement/simplifying if comparing two strings), but just want to make sure it is the case and not any other error.
> 
> https://github.com/Satellite-im/Uplink/blob/d1326eba157d472d2b3db3dc3e6761079c9daa67/common/src/state/mod.rs#L1632-L1638

yes was some out of bounds stuff
