### ISSUE TITLE
bug(ui): update loading indicator when removing/blocking a friend 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1706]
**Issue:**
When you remove a friend and the button goes to grey to indicate loading, the loading indicator and remove friend icon will both show

**OS:**
All

**Screenshot and steps to reproduce:**

- Go to Friends page
- Remove friend
- Notice button 

<img width="372" alt="Screenshot 2024-01-12 at 3 21 01 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/a670eea4-fb0d-42f4-ab87-2bfddb3ca1ba">
<img width="961" alt="Screenshot 2024-01-12 at 3 24 39 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/7a6e7a76-54ef-4a63-b738-3c0dbdd83e42">

**Comment by stavares843** [comment]
<img width="72" alt="Captura de ecrã 2024-02-01, às 00 17 55" src="https://github.com/Satellite-im/Uplink/assets/29093946/d93824b1-8cce-495c-9ef2-d24cad0b4f6b">


updated image
