### ISSUE TITLE
task(files): display % while downloading a file

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink-UI_Kit#1718]
STR:
- go to chat
- send a file
- receive a file

specially when a file is big example 100mb, theres no indication UI wise how many % regarding the download

**Comment by dariusc93** [comment]
This can be resolved by performing the checks while polling the stream

https://github.com/Satellite-im/Uplink/blob/03cd0782de4612f3df3e69a43549c0a032ce3224/ui/src/utils/async_task_queue.rs#L150-L164
