### ISSUE TITLE
bug(chat): appears 0/1024 when copy pasting code

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink-UI_Kit#1737]
STR:
- go to chat
- copy paste the following

```python
def hello_world():
    print("Hello, World!")
```
appears 0/1024

<img width="816" alt="Captura de ecrã 2024-01-19, às 14 39 28" src="https://github.com/Satellite-im/Uplink/assets/29093946/d7f3bede-ef46-44be-9776-0b3ab7cb38c8">

macOS, m1

**Comment by Flemmli97** [comment]
should be fixed with #1705 though

**Comment by stavares843** [comment]
it wasn't, and it was the same in dev as well
