### ISSUE TITLE
bug(chat): external resource inclusion

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink-UI_Kit#1744]
STR:
- go to chat
- send this

```
![External Image](http://malicious-site.com/image.jpg)
```

display like this

<img width="789" alt="Captura de ecrã 2024-01-19, às 14 40 37" src="https://github.com/Satellite-im/Uplink/assets/29093946/92ee1127-941f-44b4-96ef-1db6cda9565c">

not sure what behavior do we prefer here

discord displays like this

<img width="225" alt="Captura de ecrã 2024-01-19, às 20 18 52" src="https://github.com/Satellite-im/Uplink/assets/29093946/688c2034-c48e-4acc-921c-92ea25a9b675">

macOS, m1

**Comment by Flemmli97** [comment]
same as #1745

**Comment by stavares843** [comment]
i only meant this


<img width="40" alt="Captura de ecrã 2024-01-29, às 19 21 28" src="https://github.com/Satellite-im/Uplink/assets/29093946/b179f232-db5b-4fac-809b-f5f65c5f454f">
