### ISSUE TITLE
bug(chat): url encoding not displaying properly

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink-UI_Kit#1745]
STR:
- go to chat
- send this

```
[GitHub](https://www.github.com) is a code hosting platform for version control and collaboration.
``` 

on the chat after sending is displaying a > after the url

<img width="755" alt="Captura de ecrã 2024-01-19, às 14 35 31" src="https://github.com/Satellite-im/Uplink/assets/29093946/2e38514d-82a6-4331-bda1-001a6dfd192c">

macOS, m1

**Comment by Flemmli97** [comment]
irrc i talked to matt about this and we wanted to not support this as this can make people "hide" urls.

we do want to maybe display the original text though

**Comment by stavares843** [comment]
<img width="771" alt="Captura de ecrã 2024-01-29, às 19 21 53" src="https://github.com/Satellite-im/Uplink/assets/29093946/a53190f5-285e-456d-a04d-cbcd0d5d9dc2">

i only meant this that extra > after the url
