### ISSUE TITLE
bug(files): when uploading a big file UI does not update properly

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink-UI_Kit#1754]
STR:
- go to files
- upload a file big like 2gb
- uploading
- says in terminal already finished 

![image](https://github.com/Satellite-im/Uplink/assets/29093946/34f09bce-ac9f-4d90-89ec-c3caeef60406)

- but UI keeps saying finishing

![image](https://github.com/Satellite-im/Uplink/assets/29093946/28bd53a1-1765-4e0c-bc38-f36e5f3d743b)

- and then if you change tabs says uploading but is not uploading anything but previous file uploaded fine

video

https://github.com/Satellite-im/Uplink/assets/29093946/8eb0c659-0e1c-4152-ad6f-aed2a50053eb

macOS, m1

**Comment by stavares843** [comment]
if you need files 2gb+

https://www.mediafire.com/folder/9971h5184vpju/Osmo_Pocket_test_files

same file i used

**Comment by Flemmli97** [comment]
its not finished actually. its still running some stuff.

its fully done when this message pops up saying:
`<file> file uploaded!`
https://github.com/Satellite-im/Uplink/blob/dev/common/src/warp_runner/manager/commands/constellation_commands.rs#L600

**Comment by stavares843** [comment]
i waited around 2 minutes and was the same would only update after changing tabs

**Comment by stavares843** [comment]
still happens on dev

**Comment by Flemmli97** [comment]
hmm i tested out with a 2gb file and while it does take a bit after reaching 100% it does finish. 
on my end took around 1,5 mins.

tbh idk what warp is doing additionally after that 100% but on uplink end it just waits for a `Progression::ProgressComplete` message from warp before finishing it completely.

**Comment by dariusc93** [comment]
> hmm i tested out with a 2gb file and while it does take a bit after reaching 100% it does finish. on my end took around 1,5 mins.
> 
> tbh idk what warp is doing additionally after that 100% but on uplink end it just waits for a `Progression::ProgressComplete` message from warp before finishing it completely.

Hmm although unlikely, but if you are generating a thumbnail for the 2gb file (if its a valid image) I can see why that might be the case, otherwise it might be waiting for it to be notified from the task to be exported, which may be related to https://github.com/Satellite-im/Warp/issues/435#issuecomment-1906928707. I do plan on implementing a different change though.

**Comment by Flemmli97** [comment]
> > hmm i tested out with a 2gb file and while it does take a bit after reaching 100% it does finish. on my end took around 1,5 mins.
> > tbh idk what warp is doing additionally after that 100% but on uplink end it just waits for a `Progression::ProgressComplete` message from warp before finishing it completely.
> 
> Hmm although unlikely, but if you are generating a thumbnail for the 2gb file (if its a valid image) I can see why that might be the case, otherwise it might be waiting for it to be notified from the task to be exported, which may be related to [Satellite-im/Warp#435 (comment)](https://github.com/Satellite-im/Warp/issues/435#issuecomment-1906928707). I do plan on implementing a different change though.

ye the file i uploaded was a plain file. not video or png.

on mac you can create files with certain sizes using `mkfile -n 2g temp_2GB_file`

**Comment by stavares843** [comment]
neat

the file i used was this one

https://www.mediafire.com/folder/9971h5184vpju/Osmo_Pocket_test_files

from https://forum.dji.com/thread-183889-1-1.html

the 2gb one

**Comment by Flemmli97** [comment]
can you try a non video one?
also does this happen on dev?

**Comment by dariusc93** [comment]
Looking over the code, it looks like it may be due to the hashing being done internally and while running it in debug, it does take longer with a larger file. Running in release does speed it up, however I may make changes to optimize this.
