### ISSUE TITLE
bug(chat): user cannot type anything on search users input from create/edit group modal

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink-UI_Kit#1791]
Steps to reproduce:

1. Login with a user with friends added before
2. Go to create group chat
3. In modal, try to enter any value into User Search Input field from Create Group Modal. Cursor is moved to Group name input so user is not able to filter users by name here

1. Login with a user with friends added before
2. Go to create group chat
3. Select the checkbox of any friend and click on Create Group
4. Go to the Group Chat and then Edit Group
5. On Edit Group Modal, try to enter any value into User Search Input field from Edit Group Modal. Cursor is moved to Group name input so user is not able to filter users by name here

Happening on MacOS after changes were merged for focus on Edit/Create Group

https://github.com/Satellite-im/Uplink/assets/35935591/ea5cb4e7-43f9-4f65-a21f-c9917a6ce98f

https://github.com/Satellite-im/Uplink/assets/35935591/3cf4e6a1-ece8-4a06-993c-fb8d9b70dc92

**Comment by stavares843** [comment]
Reverted both prs
