### ISSUE TITLE
bug(chat): Glitch when sending Youtube link

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1840]
**Issue:** When you send a Youtube link in chat. there seems to be a little glitch after sending before preview appears 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/d931aa56-d6dc-4e54-a0ed-8238c76bd2c7

**Comment by stavares843** [comment]
no longer happens
