### ISSUE TITLE
bug(keyBindings): Alt always appears first when mapping keybindings 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1845]
**Issue:**
Not 100% sure if this is how we had it intended or if its a bug but Luis had pointed out that when you set a custom keybinding like Control+Shift+Alt+something it will always appear as Alt+Control+Shift like its in alphabetic order instead of the intended order set by the user. 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/27301d5c-42b8-459d-8588-05dec3785ce1

**Comment by luisecm** [comment]
Same happens with Shift... If you send Shift + Ctrl + A (in this order) as custom keybind, it will be mapped to Ctrl + Shift + A

**Comment by lgmarchi** [comment]
I will take a look on it
