### ISSUE TITLE
bug(Groups): Modal closes after adding/removing someone from group

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1853]
**Issue:** When adding or removing a member from your group, the modal will close when person is selected. Previously how we had it on dev was after selecting a person to add/remove the modal would remain open 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/6878739d-9439-4925-851e-016c6dfda8b2

**Comment by stavares843** [comment]
fixed here https://github.com/Satellite-im/Uplink/pull/1886
