### ISSUE TITLE
bug(keybinds): Close Inspector keyboard shortcut not working on Windows

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/Uplink-UI_Kit#1860]
Note 1: Keyboard shortcut is working for opening Web Inspector on Windows, but when sending keyboard shortcut to close Inspector on Windows, nothing happens

Note 2: Keyboard shortcut works correctly on macos

1. Login with any user
2. Enable Developer Settings
3. Enable Developer Mode
4. Press Control + Shift + I - Web Inspector is opened
5. Again, press Control + Shift + I - Web Inspector is not closed

**Comment by lgmarchi** [comment]
/// Close the web inspector which is usually called dev tool.
  ///
  /// ## Platform-specific
  ///
  /// - **Windows / Android / iOS:** Not supported.
  #[cfg(any(debug_assertions, feature = "devtools"))]
  pub fn close_devtools(&self) {
    self.webview.close_devtools();
  }

  /// Gets the devtool window's current visibility state.
  ///
  /// ## Platform-specific
  ///
  /// - **Windows / Android / iOS:** Not supported.
  #[cfg(any(debug_assertions, feature = "devtools"))]
  pub fn is_devtools_open(&self) -> bool {
    self.webview.is_devtools_open()
  }
  
  It is not supported on Windows unfortanely.

**Comment by luisecm** [comment]
Closing this issue for now, based on comment from @lgmarchi since this is not supported by Wry yet
