### ISSUE TITLE
bug(files): UI Freezes when uploading the same file twice 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1864]
**Issue:** When you drag the same file to the "files" section multiple times (rapidly) the UI will have lingering dialog boxes for uploads that will never finish and this error appears in log 

2024-02-20 13:21:13 | ERROR | common\src\warp_runner\manager\commands\constellation_commands.rs:449 | Error when upload file: FileExist
2024-02-20 13:21:13 | DEBUG | WARP CMD: Constellation { UploadFiles { files_path: ["C:\\Users\\xileh\\OneDrive\\Pictures\\MblWpprs\\D7292-Digital-Falcon-Mobile-Wallpaper-Ep-4.jpg"] }  }

**OS:**
Windows

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/840c2a7a-7fd6-4399-8778-bff7e8985a6d

**Comment by lgmarchi** [comment]
@phillsatellite Is easy to replicate this bug? I was not able to replicate it

**Comment by Flemmli97** [comment]
i was also not able to replicate it. though with some recent changes when an error occurs now the file will have it displayed that an error occured.

**Comment by phillsatellite** [comment]
Havent been able to replicate and neither has Sara. @XileHorizon was the original person to find this bug so I asked him to try to replicate again, if he cant I will close ticket 👍
