### ISSUE TITLE
task(ui): Add loading indicator to Create Account 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1868]
**Issue:** Sometimes it can take a decent amount of time for the app to load after clicking Create Account. We should add the loading indicator we have to this function as well, to let the user know that the app is working and it may take a few moments

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/840f696b-8678-4b50-be89-8a3ade928adc

**Comment by stavares843** [comment]
added here https://github.com/Satellite-im/Uplink/pull/1898
