### ISSUE TITLE
task(files): File Upload UI Adjustments

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/Uplink-UI_Kit#1890]
A few changes could be made to the file queue to improve the design from my initial mockups.

For starters, the files in the queue could use a little tweaking:
 - Remove the icon; there is no real reason to keep it other than aesthetics, and keeping it means less space for the file name, which is more useful information.
 - Move the download percentage underneath the progress bar and add more detail to give the file name more space and give the user more information.
 - Decrease the height of the progress bar to make extra space for the download percentage underneath.

The queue itself could be adjusted to look more similar to the call UI by increasing the rounding in the corners on the top and removing the rounding on the bottom when docked to the sidebar.
<table>
   <tr>
    <td><p>Before:</p></td>
    <td><p>After:</p></td>
  </tr>
  <tr>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/3d92a460-1114-4509-9c6c-33ee58234d1c" width="300"></td>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/439a8c6c-9dcd-47d2-9d3e-9aa08b8d5e17" width="300"></td>
  </tr>
<tr>
    <td><p>Call UI:</p></td>
  </tr>
<tr>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/bb50f709-2e3d-450c-99f5-29aa088af653" width="300"></td>
  </tr>
</table>

 When the queue is revealed by right-clicking on the files page, there is a strange container around it. Moving the queue out of that container would look much better.

<table>
   <tr>
    <td><p>Before:</p></td>
    <td><p>After:</p></td>
  </tr>
  <tr>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/340bb519-45d1-46f8-9340-233d1e45059b" width="300"></td>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/32613a40-945c-44da-bbc0-99d5e2092bf3" width="300"></td>
  </tr>
</table>

The queue should also be collapsable. Currently, in the event of several file uploads, it can easily cover the entire sidebar, but making it capable of condensing would solve that problem. The collapsed queue should have a progress bar that functions similarly to the progress ring around the files button when the user is not on the files page.

<table>
   <tr>
    <td><p>Open:</p></td>
    <td><p>Collapsed:</p></td>
  </tr>
  <tr>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/1542579e-d776-4337-8bd2-c48f6eddaa92" width="300"></td>
    <td><img src="https://github.com/Satellite-im/Uplink/assets/33043119/52e41d38-874e-406d-a26c-d6630c58777e" width="300"></td>
  </tr>
</table>

**Comment by Flemmli97** [comment]
~~adding to it:~~
~~make the ui scrollable?~~
~~for cases with a lot of files~~

done in original pr

**Comment by XileHorizon** [comment]
> adding to it: make the ui scrollable? for cases with a lot of files

Yeah for sure, once it gets to a point where all of the files can no longer be viewed it should be scrollable.
