### ISSUE TITLE
bug(ui): Messages w/ just emojis should appear big 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1897]
**Issue:** When you send a message with just emoji's the message should appear bigger. This is working fine if you send a message with just one emoji, but if you add multiple the message shows up as the incorrect size 

**OS:**
All

**Screenshot:**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/8ae7b2de-7fda-4dfe-9baf-2083555ea4b6)

**Comment by stavares843** [comment]
works fine now
