### ISSUE TITLE
task(chat): User should be able to click out of edit message

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1941]
**Issue:**
If you decide that you no longer want to edit the message you are editing you are forced to switch to another chat and then come back to active one to be able to close the edit message modal. Instead we should let the user be able to just click out of editing message 

**OS:**
MacOS
Windows
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/533a887c-61a3-45a5-8987-f26a98e0c9b7

**Comment by stavares843** [comment]
agree
