### ISSUE TITLE
task(files): Show chat names in the Chat_Media folder 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1956]
**Issue:**
Not sure how hard this would be or if it is even possible but it would be really neat if in the Chat_Media folder within the Files page we displayed the name of the chat rather than the string of letters and numbers 

**OS:**
Windows
MacOS
Linux

**Screenshot:**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/dedf42a5-8e1b-41e7-82dc-c4bf81df40f4)

**Comment by phillsatellite** [comment]
And again something Sheldon had mentioned is that we might face some issues if someone changes their name, example if the chat folder with Sara is named Sara and she changes her name to QA Robot would the folder also update with the newest name?

**Comment by dariusc93** [comment]
These directories are reflected towards the conversation itself, not the user. In my opinion, it should be left as is but instead have another layer on top of the directories that would check to see if the ids under that directory are a conversation and if so, attempt to resolve it and use the conversation name. If a conversation name isnt set (which by default a group chat doesnt have conversation name set, and direct messaging dont have names (yet)), leave as is.
